"""
SRE Agent CLI Entrypoint Application (sre-agent).

Commands:
  sre-agent init [path]               Scaffolds declarative sre-agent.yaml config in target repo
  sre-agent run [--incident FILE]     Triggers autonomous triage investigation
  sre-agent webhook [--port PORT]     Launches real-time webhook ingestion server
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
import yaml

from agent.subagents.repo_profiler import profile_repository


def init_command(target_dir: Path | str) -> Path:
    """Scaffold sre-agent.yaml configuration in target repository directory."""
    root = Path(target_dir).resolve()
    if not root.exists():
        root.mkdir(parents=True, exist_ok=True)

    config_path = root / "sre-agent.yaml"
    if config_path.exists():
        print(f"⚠️  Configuration file already exists at: {config_path}")
        return config_path

    # Introspect target repository to pre-fill configuration fields
    print(f"🔍 Introspecting repository at '{root.name}'...")
    profile = profile_repository(root)

    config_data = {
        "service_name": profile.service_name,
        "language": profile.language,
        "framework": profile.framework,
        "entrypoint": profile.entrypoint,
        "build_command": profile.build_command,
        "test_command": profile.test_command,
        "log_source": profile.log_source,
    }

    yaml_text = (
        f"# Declarative SRE Agent Configuration for {profile.service_name}\n"
        f"# Generated by `sre-agent init`\n\n"
        + yaml.dump(config_data, default_flow_style=False, sort_keys=False)
    )

    config_path.write_text(yaml_text, encoding="utf-8")
    print(f"✅ Successfully created '{config_path}'!\n")
    print("Pre-filled Configuration:")
    print("----------------------------------------")
    print(yaml_text)
    print("----------------------------------------")
    print("Next step: Run `sre-agent run --incident payload.json` to start an investigation.")
    return config_path


def run_command(incident_file: str | None, repo_path: str, dry_run: bool, model: str) -> None:
    """Execute triage investigation on target repository."""
    root = Path(repo_path).resolve()
    print(f"🚀 Launching SRE Agent investigation on '{root.name}' (dry_run={dry_run})...")

    # Load incident payload
    incident_context = ""
    if incident_file:
        pfile = Path(incident_file)
        if pfile.exists():
            try:
                data = json.loads(pfile.read_text(encoding="utf-8"))
                incident_context = (
                    f"Incident details:\n"
                    f"Title: {data.get('title')}\n"
                    f"Severity: {data.get('severity')}\n"
                    f"Timestamp: {data.get('timestamp')}\n\n"
                    f"Stack Trace:\n```\n{data.get('stack_trace')}\n```\n\n"
                    f"Logs:\n" + "\n".join(data.get("logs", []))
                )
            except Exception:
                incident_context = pfile.read_text(encoding="utf-8")
        else:
            print(f"⚠️  Incident file '{incident_file}' not found. Proceeding with default context.")

    if not incident_context:
        incident_context = "Default Incident Alert: System latency spike and unhandled exception."

    from agent.orchestrator import create_orchestrator

    agent = create_orchestrator(model_name=model)
    config = {"configurable": {"thread_id": f"cli-{root.name}"}}
    input_state = {
        "messages": [],
        "incident_context": incident_context,
        "sandbox_id": "",
        "subagent_outputs": [],
        "selected_bug": "",
        "repro_result": "",
        "patch_result": "",
        "diagnosis": "",
        "phase": "start",
        "grader_attempts": 0,
        "grader_feedback": "",
        "approval_diff": "",
        "rejected_hypotheses": [],
        "repo_profile": {},
        "plan_only": dry_run,
    }

    try:
        res = agent.invoke(input_state, config=config)
        print("\n============================================================")
        print("📋 FINAL TRIAGE DIAGNOSIS")
        print("============================================================")
        print(res.get("diagnosis", "No diagnosis returned."))
    except Exception as e:
        print(f"❌ Execution error: {e}", file=sys.stderr)


def webhook_command(port: int, host: str) -> None:
    """Launch real-time webhook receiver server."""
    print(f"📡 Starting SRE Agent Webhook Receiver on http://{host}:{port}...")
    import uvicorn
    uvicorn.run("scripts.webhook_receiver:app", host=host, port=port, reload=True)


def main() -> None:
    """CLI Entrypoint."""
    parser = argparse.ArgumentParser(
        prog="sre-agent",
        description="Autonomous SRE Incident-Triage Agent CLI",
    )
    subparsers = parser.add_subparsers(dest="command", help="Command to execute")

    # init command
    init_parser = subparsers.add_parser("init", help="Scaffold sre-agent.yaml in target repo")
    init_parser.add_argument("path", nargs="?", default=".", help="Target repository directory (default: current directory)")

    # run command
    run_parser = subparsers.add_parser("run", help="Run triage investigation")
    run_parser.add_argument("--incident", "-i", help="Path to incident JSON payload file")
    run_parser.add_argument("--repo", "-r", default=".", help="Target repository path (default: current directory)")
    run_parser.add_argument("--dry-run", action="store_true", help="Run in plan-only dry-run mode without modifying files")
    run_parser.add_argument("--model", default="llama-3.3-70b-versatile", help="Groq model name to use")

    # webhook command
    wh_parser = subparsers.add_parser("webhook", help="Launch real-time webhook receiver server")
    wh_parser.add_argument("--port", type=int, default=8000, help="Port to listen on (default: 8000)")
    wh_parser.add_argument("--host", default="0.0.0.0", help="Host interface (default: 0.0.0.0)")

    args = parser.parse_args()

    if args.command == "init":
        init_command(args.path)
    elif args.command == "run":
        run_command(args.incident, args.repo, args.dry_run, args.model)
    elif args.command == "webhook":
        webhook_command(args.port, args.host)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
